### PR TITLE
add_ped.py: Update isa_tab fields 'family', 'sex' and 'disease status' from pedfile information when donor is already existent

### PR DESCRIPTION
**Pull request by your-highness**
Dear @holtgrewe ,

This is my working solution to fix issue #1 . Please merge if ok.

Best,
Johannes

### CODE REVIEW

**Comment by holtgrewe** [comment]
LGTM; I'll have to merge it through our internal repository, though. Give me until the beginning of next week.

**Comment by your-highness** [comment]
Thanks! _The solution looks fine to you?_ 

In the meantime, I am using my fork in production right now 😊

**Comment by your-highness** [comment]
Any update on this pull request?

**Comment by holtgrewe** [comment]
I believe it's merged in teh `master` without being closed here.

**Comment by JPatrickPett** [comment]
yes, that's true... it's merged in commit 41b24e00a69c35cb88f924ed6b6930b9e9853823

**Pull request closed without merging**
