### PR TITLE
fix: add space between value and unit symbol for file size formatting

### PR DESCRIPTION
**Pull request by sellth**
As specified by ISO 31-0. ;-)

### CODE REVIEW

**Comment by holtgrewe** [comment]
Hm, one could make the argument that number and unit form a token that is easier to process as terminal text. E.g., copy it by double-clicking.

Also cf. 

```
# ls -lh | head -n 1
total 2.2G
df -h | head -n 2
Filesystem                              Size  Used Avail Use% Mounted on
udev                                     32G     0   32G   0% /dev
```

**Comment by holtgrewe** [comment]
Further evidenc, Python's tqdm prints by default `4.38s/it`

**Comment by sellth** [comment]
Good point, but what if I only want to copy the number part? Also, there seems to be another discussion ongoing: https://github.com/tqdm/tqdm/issues/825

**Comment by holtgrewe** [comment]
If you think it's actually an improvement then please go ahead and merge it. It's not worth the time discussing/thinking about.

**Review by holtgrewe — APPROVED** [review]

**Comment by holtgrewe** [comment]
;-)

**Comment by sellth** [comment]
This is mainly a nitpick of mine which I probably would've ignored if it weren't Friday afternoon. Let's wait a bit to see if there are more comments on this pressing issue. :-)

**Pull request merged**
