### PR TITLE
New snappy check for irods content

### LINKED ISSUE #56: Write cubi-tk snappy check for irods content
**Is your feature request related to a problem? Please describe.**
It would be important to check whether all files from a snappy pipeline run have been persisted correctly into iRODS. This way one could reliably remove local files.

**Describe the solution you'd like**
Check that the expected files from a snappy run are

- in SODAR iRODS in the configured project
- have the correct checksum
- possibly, check that there are no extra files and warn about them

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by eudesbarbosa**
closes #56 

**Changes**
* New routine to compare remote and local files, call: `cubi-tk snappy check-remote <UUID>`.
* Previous available check routine renamed, call: `cubi-tk snappy check-local <UUID>`.

### CODE REVIEW

**Comment by holtgrewe** [comment]
Hi, I'm just putting stuff here as I see it. There are a lot of commits here that make the PR hard to read. Could you rebase to current master?

**Comment by holtgrewe** [comment]
> Hi, I'm just putting stuff here as I see it. There are a lot of commits here that make the PR hard to read. Could you rebase to current master?

Ah, never mind, you started off my WIP branch.

**Comment by holtgrewe** [comment]
Hi, the semantics look fine. I have one proposal for improvement of semantics and general info comments:

1. I would suggest rather going for iquest or the python irods library equivalent.
    - You can perform queries like `SELECT coll_name, data_name WHERE coll_name LIKE "/someZone/prefix/.../%"`. You then just have one API call instead of many ils -r calls that might (and show error debug messages because of return code !=0 that are not problems per se).
    - With the python irods library you will also be able to just read the .md5 files from irods directly without calling to iget.
2. maybe cwd back to the directory that has ".snappy_pipeline" and "ngs_mapping" and such as sub directories automatically.
3. overall the semantics are correct. It might be useful to print warnings in the case that there are two files (from any sample!) that have the same checksum (except if this is the checksum of the empty file/string).
4. I think it would be helpful if the reported file lists were sorted so it is simpler to visually group them.

I'm also seeing a lot of missing ".fastq.gz.md5" files. I believe the `itransfer-raw-data` takes the .md5 files from the link target in the input links folder. Also see https://github.com/bihealth/snappy-pipeline/issues/79.

**Comment by eudesbarbosa** [comment]
I messed up the PR with a rebase. Real change:
- [ ] `cubi_tk/snappy/__init__.py`
- [ ] `cubi_tk/snappy/check_local.py`
- [ ] `cubi_tk/snappy/check_remote.py`
- [ ] `cubi_tk/snappy/common.py`
- [ ] `tests/conftest.py`
- [ ] `tests/data/*`
- [ ] `tests/test_snappy_check_remote.py`

**Pull request merged**
