### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by holtgrewe**

### CODE REVIEW

**Comment by holtgrewe** [comment]
@eudesbarbosa @ericblanc20 some small fixes... By the merge conflict that I had to resolve, it becomes apparent to me that we need to harmonize the sequencing type vocabulary.

**Review by eudesbarbosa — APPROVED** [review]
LGTM

...maybe rebase this one instead of squash?

**Review by ericblanc20 — COMMENTED** [review]
RNA data is a problem to me, because there are so many different assay types.

How should we harmonize cubi-tk with [biomedsheets](https://github.com/bihealth/biomedsheets/blob/306b67242ceb93baa3dd90fac91eb1189f93e807/biomedsheets/io_tsv/base.py#L38-L39)?

**Comment by holtgrewe** [comment]
> How should we harmonize cubi-tk with biomedsheets?

I think we should just use whatever biomedsheets uses for now. So I need to move from `RNA_seq` to `mRNA_seq`.

**Pull request merged**
